### PR TITLE
Proposed fix for CSS width of popup toolbar in #52

### PR DESCRIPTION
**Pull request by jywarren**
This would need compiling to be completed if approved - i'd love help if possible! Thanks!

### CODE REVIEW

**Comment by justinmanley** [comment]
thanks for sending this bugfix, Jeff! Let me know if you need me to do a new npm release with the fix included.

**Comment by jywarren** [comment]
Hi thanks! I just don't have the full lib set up locally so I didn't do the
build process before submitting this, I think it could use a "npm build" or
whatever the minifying command is to reflect this into the min version of
the stylesheet. I'm happy to do it now that you approved it, but if it's
easier for you before releasing a new npm version I'd also appreciate the
help!

**Comment by justinmanley** [comment]
yup, I already recompiled the CSS (see the master branch). Just lmk if you need a new npm release in order to integrate this into your workflow!

**Comment by jywarren** [comment]
Oh awesome. Didn't see it in the PR so wanted to double check. Yes, a new
release would be helpful!

**Comment by justinmanley** [comment]
done! the latest version is now "0.4.0-alpha.2."

https://www.npmjs.com/package/leaflet-toolbar

**Comment by jywarren** [comment]
awesome, thank you!

**Pull request merged**
