### PR TITLE
Make that L.Toolbar inherits from L.Layer if it exists

### PR DESCRIPTION
**Pull request by yohanboniface**
This adds minimal compat with Leaflet master.

Thanks :)

### CODE REVIEW

**Comment by yohanboniface** [comment]
It's failing on https://github.com/Leaflet/Leaflet.toolbar/pull/22

**Comment by manleyjster** [comment]
@yohanboniface - Could you explain a bit more?

Where is the need to inherit from L.Layer coming from?

**Comment by yohanboniface** [comment]
Sure :)

The Leaflet master`map.addLayer` [expects](https://github.com/Leaflet/Leaflet/blob/master/src/layer/Layer.js#L75)  the added layer to have a `_layerAdd` method, which, in the inheritance toolchain comes from `L.Layer` (and which is responsible to call the `onAdd` method then).

So I thought that, as soon as we use `map.addLayer`, we should conform to the inheritance toolchain.

Given that the toolbar is not really a layer but more of a control, maybe a stronger fix in the future would be to stop using `addLayer`, but I'm ensure how we can support both 0.7 and master this way.

What do you think?

**Comment by yohanboniface** [comment]
ping @manleyjster :)

**Comment by manleyjster** [comment]
@yohanboniface - Will this PR make a difference to you immediately (i.e. are you currently using Leaflet master?), or are you anticipating future issues that will arise once Leaflet 1.0 is released?

If this PR is anticipatory, I'd rather hold off on merging it for the time being, since I expect that there will be a great many changes to be made once Leaflet 1.0 comes out. I'd rather wait to work on 1.0 compatibility until the state of the library is settled and we can look at the whole pictures.

This is great, though, because it's getting the discussion started!

**Comment by yohanboniface** [comment]
A bit of both ;)

We are close to the 1.0 beta version: https://github.com/Leaflet/Leaflet/milestones/1.0-beta1
And I'm starting porting uMap on Leaflet 1.0: https://github.com/yohanboniface/Leaflet.Storage/issues/94 and I want to switch to Leaflet.Toolbar in the meantime (because it needs more interactions for multipolgon/polyline support, and I want to use the popup mode :) ).

So as you prefer, I can maintain a Leaflet1.0 branch on my own fork in the meantime also. But I think such a huge milestone (Leaflet 1.0) needs to be done also by the community, porting plugins one by one before the release, so we can have feedback and bug report before issuing the release. For sure, you can wait for the first official beta. But given that those changes are both 0.7 and 1.0 compliant, I would merge, to help pushing the community forward, and help people that start migrating by anticipation ;)

Anyway, your choice :)

**Comment by yohanboniface** [comment]
http://leafletjs.com/2015/07/15/leaflet-1.0-beta1-released.html ;)

**Comment by mourner** [comment]
Since the changes are minimal, I'd say let's rebase and merge into master.

**Pull request merged**
